alias s='sudo apt-get install'
alias remove='sudo apt-get remove'
alias update='sudo apt-get update'
alias pkglist='dpkg --get-selections'
alias -s {avi,mpeg,mpg,mov,m2v}=vlc
alias -s {pdf,djv,fb2}=evince
alias -s {mp3,ogg,flac}=rhythmbox
alias -s {odt,doc,docx,sxw,rtf}=libreoffice
alias -s {bmp,jpg,jpeg,gif,png}=photoqt
alias -s {cpp, h, rb, txt}=subl